### PR TITLE
Fix invalid tuition time parsed successfully

### LINKED ISSUE #75: Tuition time may be invalid
Not catching invalid tuition times such as:
- Time outside 24hrs format (eg. 2500)
- Start time is later than end time (eg. 2000-1800)

### PR DESCRIPTION
**Pull request by davidchongg**
Fixes #75

Now validates that the input time is in the correct 24-hour format (HHMM-HHMM), ensuring:
- The hours are between 00 and 23.
- The minutes are between 00 and 59.

A new method, isStartTimeEarlierThanEndTime, has been added. This method compares the start time and end time to ensure that the start time is not later than the end time. This logic is necessary because the regex alone cannot perform this comparison.

### CODE REVIEW

File: src/main/java/seedu/address/model/person/TuitionTime.java [hunk 1]
```diff
@@ -12,7 +12,8 @@ public class TuitionTime {
 
     public static final String MESSAGE_CONSTRAINTS =
             "Tuition time must be in the format: 'DayOfWeek, HHMM-HHMM'.\n"
-                    + "Day must be Monday to Sunday (case-insensitive), and times must be in 24-hour format.\n"
+                    + "Day must be Monday to Sunday (case-insensitive), times must be in 24-hour format and "
+                    + "start time cannot be later than end time.\n"
```
Comment (brvndonkoh) [inline src/main/java/seedu/address/model/person/TuitionTime.java:16]: Good catch David! I'm pretty sure some users may have typos and wouldn't recognize until later.

**Review by brvndonkoh — APPROVED** [review]
