### PR TITLE
Fix list command

### LINKED ISSUE #50: Change list command to include field prefix for all commands

### PR DESCRIPTION
**Pull request by davidchongg**
Fixes #50 

Change all list command to include prefix. Additionally fixed and improved test coverage for ListCommand and ListCommandParser.

### CODE REVIEW

**Review by huangtian666 — APPROVED** [review]
LGTM. Good job!

**Review by brvndonkoh — APPROVED** [review]
Great job adhering to the coding conventions and organising your imports properly. Keep up the good work!

File: src/main/java/seedu/address/logic/commands/ListCommand.java [hunk 1]
```diff
@@ -17,6 +17,10 @@ public class ListCommand extends Command {
 
     public static final String MESSAGE_SUCCESS = "Listed all students";
     public static final String EMPTY_LIST = "No student found.";
+    public static final String MESSAGE_USAGE = COMMAND_WORD + ": Lists all persons with keyword (case-insensitive) "
```
Comment (jeronkk) [inline src/main/java/seedu/address/logic/commands/ListCommand.java:20]: This comment is pretty long. When displayed in the the ResultDisplay.java, the box is too small and requires the user to scroll which might be inconvenient.
image

**Review by jeronkk — APPROVED** [review]
Great work overall! Have one comment to look into but otherwise great work.
