### PR TITLE
Fix bug add

### LINKED ISSUE #68: Improve clarity of add feature

### LINKED ISSUE #70: Improve isSamePerson() in Person.java
Before:
- cannot add person with same name but other different attributes

After:
- can add people with same name but different phone number
- people can have the same name but their phone numbers are different. phone number can uniquely identify a person

### PR DESCRIPTION
**Pull request by huangtian666**
Fixes #68 
Fixes #70

### CODE REVIEW

**Review by brvndonkoh — APPROVED** [review]
Nice Job.

File: src/main/java/seedu/address/model/person/Person.java [hunk 1]
```diff
@@ -77,7 +77,7 @@ public boolean isSamePerson(Person otherPerson) {
         }
 
         return otherPerson != null
-                && otherPerson.getName().equals(getName());
+                && otherPerson.getName().equals(this.name) && otherPerson.getPhone().equals(this.phone);
```
Comment (davidchongg) [inline src/main/java/seedu/address/model/person/Person.java:80]: good work on this

**Review by davidchongg — APPROVED** [review]
