### PR TITLE
Correct sort by name desc logic for name field

### LINKED ISSUE #85: Bug: `sort by name desc` returns incorrect order for full names
When the Contact has more than 2 names for example: "Brandon Koh" and "David Chong", when `sort by name desc` is called, TutorProMax returns the names in the wrong order.

### LINKED ISSUE #87: Help page in TutorProMax
Under the SortCommand in help, it is better to standardize the users to type in `sort by name asc` rather than `sort name asc` to prevent confusions as it is more intuitive

### LINKED ISSUE #88: Error message in Delete Command
When an index out of bounds is selected, the following message is shown:
" The person index provided is invalidPlease provide a number between 1 and 5"

### PR DESCRIPTION
**Pull request by brvndonkoh**
This PR fixes a bug where the sort by name desc command returns names in the wrong order when contacts have full names (e.g., "Brandon Koh", "David Chong").

When sorting by name in descending order, the SortCommand logic reverses the comparator twice. This effectively cancels the intended reverse order and results in the list being sorted as if in ascending order.

✅ Fix
- Removed the duplicate call to comparator.reversed() in SortCommand.java.
- Now, the comparator is reversed exactly once when ascending is false.

Fixes #85 
Fixes #87 
Fixes #88

### CODE REVIEW

**Review by huangtian666 — APPROVED** [review]
LGTM!

File: src/main/java/seedu/address/ui/CommandConfig.java [hunk 1]
```diff
@@ -52,8 +52,8 @@ public static List<CommandUsageInfo> getAllCommands() {
                 ),
                 new CommandUsageInfo(
                         "sort - Sort all contacts according to a field entered by user (ascending by default)",
-                        "sort [FIELD] asc/desc",
-                        "sort name asc or sort phone desc"
+                        "sort by [FIELD] asc/desc",
```
Comment (davidchongg) [inline src/main/java/seedu/address/ui/CommandConfig.java:55]: nice work here

**Review by davidchongg — APPROVED** [review]

**Review by jeronkk — APPROVED** [review]
Good catch man!
